/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GymbrosRouteImport } from './routes/gymbros'
import { Route as DashRouteImport } from './routes/dash'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AscendantRouteImport } from './routes/ascendant'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GymbrosRoute = GymbrosRouteImport.update({
  id: '/gymbros',
  path: '/gymbros',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendantRoute = AscendantRouteImport.update({
  id: '/ascendant',
  path: '/ascendant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascendant': typeof AscendantRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dash': typeof DashRoute
  '/gymbros': typeof GymbrosRoute
  '/journal': typeof JournalRoute
  '/metrics': typeof MetricsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascendant': typeof AscendantRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dash': typeof DashRoute
  '/gymbros': typeof GymbrosRoute
  '/journal': typeof JournalRoute
  '/metrics': typeof MetricsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascendant': typeof AscendantRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dash': typeof DashRoute
  '/gymbros': typeof GymbrosRoute
  '/journal': typeof JournalRoute
  '/metrics': typeof MetricsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascendant'
    | '/auth'
    | '/coach'
    | '/dash'
    | '/gymbros'
    | '/journal'
    | '/metrics'
    | '/nutrition'
    | '/photos'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascendant'
    | '/auth'
    | '/coach'
    | '/dash'
    | '/gymbros'
    | '/journal'
    | '/metrics'
    | '/nutrition'
    | '/photos'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/ascendant'
    | '/auth'
    | '/coach'
    | '/dash'
    | '/gymbros'
    | '/journal'
    | '/metrics'
    | '/nutrition'
    | '/photos'
    | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscendantRoute: typeof AscendantRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  DashRoute: typeof DashRoute
  GymbrosRoute: typeof GymbrosRoute
  JournalRoute: typeof JournalRoute
  MetricsRoute: typeof MetricsRoute
  NutritionRoute: typeof NutritionRoute
  PhotosRoute: typeof PhotosRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gymbros': {
      id: '/gymbros'
      path: '/gymbros'
      fullPath: '/gymbros'
      preLoaderRoute: typeof GymbrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascendant': {
      id: '/ascendant'
      path: '/ascendant'
      fullPath: '/ascendant'
      preLoaderRoute: typeof AscendantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscendantRoute: AscendantRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  DashRoute: DashRoute,
  GymbrosRoute: GymbrosRoute,
  JournalRoute: JournalRoute,
  MetricsRoute: MetricsRoute,
  NutritionRoute: NutritionRoute,
  PhotosRoute: PhotosRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
